---
# tasks file for mightydok-bareos-sd

# Add bareos repo key
-   name: Add Bareos repository key
    apt_key:
        url: "http://download.bareos.org/bareos/release/latest/xUbuntu_16.04/Release.key"
        state: present

# Add bareos repo
-   name: Add Bareos repository
    apt_repository:
        repo: deb http://download.bareos.org/bareos/release/latest/xUbuntu_16.04/ /
        state: present

# Install bareos-sd packages
-   name: Install bareos-sd pakages
    apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
    with_items: "{{ mightydok_bareos_sd_packages }}"

# Place config for bareos-dir and bareos-mon
-   name: Place config for bareos-sd
    template:
        src: templates/{{ item }}.j2
        dest: /etc/bareos/bareos-sd.d/director/{{ item }}
        owner: bareos
        group: bareos
        mode: 0750
    with_items:
        - bareos-dir.conf
        - bareos-mon.conf
    notify: restart bareos-sd

# Place config for bareos-dir and bareos-mon
-   name: Place config for storage
    template:
        src: templates/bareos-sd.conf.j2
        dest: /etc/bareos/bareos-sd.d/storage/bareos-sd.conf
        owner: bareos
        group: bareos
        mode: 0750
    notify: restart bareos-sd

# Create storage directory
-   name: Create storage directories
    file: "{{ item.archive_device }}"
        owner: bareos
        group: bareos
        mode: 0750
        state: present
    with_items: "{{ mightydok_bareos_sd_device }}"

# Copy storage servers templates
-   name: Create bareos-sd config files
    template:
        src: "{{ item }}"
        dest: /etc/bareos/bareos-sd.d/{{ item | basename | regex_replace('\.conf.j2','') }}/ansible.conf
        owner: bareos
        group: bareos
        mode: 0750
    with_fileglob: ../templates/bareos/*.j2
    notify: restart bareos-sd

# Autostart bareos-sd
-   name: Ensure bareos-sd autorun
    service:
        name: bareos-sd
        enabled: yes
